org.gradle.jvmargs=-Xmx1G
org.gradle.caching=false
org.gradle.configuration-cache=false
# Plugin Metadata
plugin_group=James Peters
plugin_description=An example plugin for Hytale!
plugin_author=James Peters
plugin_website=https://discord.hytale-modding.info
plugin_main_entrypoint=com.jamesdpeters.voidstorage.VoidStoragePlugin
server_version=*
