org.gradle.jvmargs=-Xmx1G
org.gradle.caching=false
org.gradle.configuration-cache=false
# Plugin Metadata
plugin_group=JamesPeters
plugin_description=Adds the Chest of the Void, a soulbound storage chest, to the game.
plugin_author=James Peters
plugin_website=
plugin_main_entrypoint=com.jamesdpeters.voidstorage.VoidStoragePlugin
server_version=*
